#!/bin/sh -euC
#
# Copyright 2023 Contributors the the zkp-audit-zokrates repository
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.

generate_times()
{
	program=$1
	awk '/^real/{print $2}' $program.log \
	| awk -vtype=$program \
	    'BEGIN{printf("%s,%d,",type,++I)}
	     NR%4{printf("%s,",$0);next}
	     {print$0;printf("%s,%d,",type,++I)}' \
	| sed 10q
}

echo program,number,compilation,setup,witness,proof
for p in balances whitelist merkle; do generate_times $p; done
