#!/bin/sh -euC

readonly default_rounds=10

usage() { >&2 echo "usage: $0 [-n rounds]"; }

measure()
{
	program=$1 log_dir=$2
	cd "audit-$program/"
	for i in $(seq $rounds); do
		echo "\n\n******** $program[$i] {{{"
		make clean all
		echo "******** }}} $program[$i]"
	done 2>&1 | tee $log_dir/$program.log
	ls -l 2>&1 | tee $log_dir/$program.sizes
	make clean
	cd ..
}


rounds=$default_rounds
while getopts hn: name; do
	case $name in
	h)      usage; exit 0;;
	n)      rounds=$OPTARG;;
	?)      usage; exit 1;;
	esac
done


my_dir=$(pwd)
cd ../
for p in balances whitelist merkle; do measure $p $my_dir; done
